server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/athens?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false

  jwt:
    secret: ${JWT_SECRET_KEY}


logging:
  level:
    '[com.attica.athens]': DEBUG
    '[org.hibernate.type]': TRACE

frontend:
  local: http://localhost:3000 # 로컬 URL 예시