name: 
on:
  push:
    branches:
      - "master"
     
jobs:
  server-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          sourece: ${{ secrets.SOURCE_FILE }}
          target: ${{ secrets.TARGET_PATH }}

      - name: Login Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWD }}

      - name: Deploy using docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_N }}/${{ secrets.DOCKER_R }}
            sudo docker-compose down
            sudo docker-compose up --build -d

      # port: ${{ secrets.SSH_PORT }} 
      #      sudo docker rm -f $(docker ps -qa)
      # - name: Deploy using docker-compose
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.AWS_IP }}
      #     username: ubuntu
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       cd ~/test2
      #       sudo git pull
      #       sudo docker-compose down
      #       sudo docker-compose up --build -d